# Generated by Django 5.1.1 on 2024-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
