# Generated by Django 5.1.1 on 2024-09-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_lista_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='url',
            field=models.URLField(max_length=3000),
        ),
    ]
