# Generated by Django 5.1.1 on 2024-09-23 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_lista_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='listWatch',
            field=models.ManyToManyField(blank=True, null=True, related_name='lista', to=settings.AUTH_USER_MODEL),
        ),
    ]
