# Generated by Django 5.1.1 on 2024-09-25 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_lista_listwatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listasCat', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listasKey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lista',
            name='listWatch',
            field=models.ManyToManyField(blank=True, null=True, related_name='listaWatch', to=settings.AUTH_USER_MODEL),
        ),
    ]
