# Generated by Django 5.1.1 on 2024-09-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_oferta_alter_lista_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='amount',
            new_name='price',
        ),
    ]
