# Generated by Django 5.1.1 on 2024-09-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_amount_oferta_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='oferta',
        ),
    ]
