# Generated by Django 5.1.1 on 2024-09-26 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_lista_price_delete_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='auctions.lista'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lista',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lista',
            name='listWatch',
            field=models.ManyToManyField(blank=True, related_name='watch_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lista',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_bids', to='auctions.bid'),
        ),
    ]
