# Generated by Django 5.1.1 on 2024-09-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_lista_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL),
        ),
    ]
